name: package-release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build:
    name: build and upload release to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # setuptools-scm needs the tags to set the version
      - uses: astral-sh/setup-uv@v10.2.0
      - name: build sdist and wheel
        run: uv build
      - name: upload to pypi
        if: github.event_name == 'release' && github.event.action == 'published'
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
