name: black

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Check formatting with black
      run: |
        pip install black==20.8b1
        # check that formatting is ok with black
        black --check .
